config/routes.rb
RailsTest1::Application.routes.draw do
  get "reminder/date"

  resources :estates

end

app/models/estate.rb
class Estate < ActiveRecord::Base
  attr_accessible :due_dates, :estate_code, :service_charge_period

  validates_uniqueness_of :estate_code

  def due_dates_list
      self.due_dates.split( ',').collect do |d| d.strip end
  end
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/estates_controller.rb
class EstatesController < ApplicationController
  # GET /estates
  # GET /estates.json
  def index
    @estates = Estate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estates }
    end
  end

  # GET /estates/1
  # GET /estates/1.json
  def show
    @estate = Estate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estate }
    end
  end

  # GET /estates/new
  # GET /estates/new.json
  def new
    @estate = Estate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estate }
    end
  end

  # GET /estates/1/edit
  def edit
    @estate = Estate.find(params[:id])
  end

  # POST /estates
  # POST /estates.json
  def create
    @estate = Estate.new(params[:estate])

    respond_to do |format|
      if @estate.save
        format.html { redirect_to @estate, notice: 'Estate was successfully created.' }
        format.json { render json: @estate, status: :created, location: @estate }
      else
        format.html { render action: "new" }
        format.json { render json: @estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estates/1
  # PUT /estates/1.json
  def update
    @estate = Estate.find(params[:id])

    respond_to do |format|
      if @estate.update_attributes(params[:estate])
        format.html { redirect_to @estate, notice: 'Estate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estates/1
  # DELETE /estates/1.json
  def destroy
    @estate = Estate.find(params[:id])
    @estate.destroy

    respond_to do |format|
      format.html { redirect_to estates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reminder_controller.rb
class ReminderController < ApplicationController
  def date
    dates = ['1st Jan 2009', '1st Feb 2009', '2nd Feb 1979', '15th Mar 1999', '21st Apr 2013', 
             '22nd Apr 2017', '29th Apr 2000', '30th Apr 2002', '29th Oct 2011', '30th Oct 2011', '24th Dec 2006']
    @estates = Estate.all
    @results = []
    dates.each do |date|
      res = remind date, @estates
      res.each do |rem|
        @results << [date, rem]
      end
    end
        
  end
    
  def remind(date,estates)
    date = Date.parse date
    results = []
    estates.each do |e|
      e.due_dates_list.each do |db_due_date|
        due_date = Date.parse "#{db_due_date} #{date.year}"
        due_date = due_date + 1.year if due_date < date #due dates must be in future
        if e.service_charge_period == "Quarterly"          
          reminder_date = due_date - 1.month
        elsif e.service_charge_period == "Twice a year"
          reminder_date = due_date - 2.months
        else
          raise "wrong service charge period in the database"
        end
        if date.between? reminder_date, due_date
          results << "#{e.estate_code} due date #{db_due_date} #{due_date.year}"
        end
      end
    end
    results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estates_helper.rb
module EstatesHelper
end

app/helpers/reminder_helper.rb
module ReminderHelper
end

app/views/estates/_form.html.erb
<%= form_for(@estate) do |f| %>
  <% if @estate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estate.errors.count, "error") %> prohibited this estate from being saved:</h2>

      <ul>
      <% @estate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :estate_code %><br />
    <%= f.text_field :estate_code %>
  </div>
  <div class="field">
    <%= f.label :service_charge_period %><br />
    <%= f.text_field :service_charge_period %>
  </div>
  <div class="field">
    <%= f.label :due_dates %><br />
    <%= f.text_field :due_dates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estates/edit.html.erb
<h1>Editing estate</h1>

<%= render 'form' %>

<%= link_to 'Show', @estate %> |
<%= link_to 'Back', estates_path %>

app/views/estates/index.html.erb
<h1>Listing estates</h1>

<table>
  <tr>
    <th>Estate code</th>
    <th>Service charge period</th>
    <th>Due dates</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estates.each do |estate| %>
  <tr>
    <td><%= estate.estate_code %></td>
    <td><%= estate.service_charge_period %></td>
    <td><%= estate.due_dates %></td>
    <td><%= link_to 'Show', estate %></td>
    <td><%= link_to 'Edit', edit_estate_path(estate) %></td>
    <td><%= link_to 'Destroy', estate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Estate', new_estate_path %>

app/views/estates/new.html.erb
<h1>New estate</h1>

<%= render 'form' %>

<%= link_to 'Back', estates_path %>

app/views/estates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Estate code:</b>
  <%= @estate.estate_code %>
</p>

<p>
  <b>Service charge period:</b>
  <%= @estate.service_charge_period %>
</p>

<p>
  <b>Due dates:</b>
  <%= @estate.due_dates %>
</p>


<%= link_to 'Edit', edit_estate_path(@estate) %> |
<%= link_to 'Back', estates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTest1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reminder/date.html.haml
%h1 Reminder#date
%p Find me in app/views/reminder/date.html.haml

%div
  - @results.each do |r|
    %p= r.inspect
%p
  = params.inspect